services:
  lucy_ros2_ws:
    build: .
    container_name: "lucy_ros2_ws_jazzy"
    image: lucy_ros2_ws:jazzy
    restart: unless-stopped
    command: tail -f /dev/null
    volumes:
      - "${LUCY}:/home/rosdev/lucy_ros2_ws"
    network_mode: host
