services:
  lucy_ros2_ws:
    build: .
    container_name: "lucy_ros2_ws_humble"
    image: lucy_ros2_ws:humble
    restart: unless-stopped
    command: tail -f /dev/null
    ports:
      - 5900:5900
    volumes:
      - "${LUCY}:/home/rosdev/lucy_ros2_ws"
