#!/bin/bash

# Creating folder

echo -ne "Creating lucy folder "
if [[ -d "lucy" ]]; then
    echo -e "\033[31mko.\033[0m"
    echo -e "The folder lucy already exists."
    exit 1
fi
mkdir -p lucy/src
cd lucy || exit 1
echo -e "\033[32mok.\033[0m"

# Cloning repositories

echo -ne "Select a cloning method for lucy repo (https/ssh): "
read -r method
method=$(echo "$method" | tr '[:upper:]' '[:lower:]')

# Cloning lucy repo

GIT=$(command -v git 2> /dev/null)
if [[ -z "$GIT" ]]; then
    echo -e "\033[31mgit not found.\033[0m"
    exit 1
fi

CURL=$(command -v curl 2> /dev/null)
if [[ -z "$CURL" ]]; then
    echo -e "\033[31mcurl not found.\033[0m"
    exit 1
fi

VCS=$(command -v vcs 2> /dev/null)
if [[ -z "$VCS" ]]; then
    echo -e "\033[31mvcs not found.\033[0m"
    exit 1
fi

clone_lucy_repo() {
    echo -ne "Cloning $1Sentience-Robotics/$2.git. "
    if ! $GIT clone "$1Sentience-Robotics/$2.git" > /dev/null 2> /tmp/lucy_init.log; then
        echo -ne "\033[31mko\033[0m"
        cat /tmp/lucy_init.log
        exit 1
    fi
    echo -e "\033[32mok\033[0m"
}

case "$method" in
    1|https|http)
        clone_lucy_repo "https://github.com/" "lucy_devtools"
        echo -ne "Cloning lucy ros packages "
        if ! $CURL -fsSL "https://raw.githubusercontent.com/Sentience-Robotics/lucy_devtools/refs/heads/master/lucy_utils/lucy.https.repos" | $VCS import src > /dev/null 2> /tmp/lucy_init.log; then
            echo -ne "\033[31mko\033[0m"
            cat /tmp/lucy_init.log
            exit 1
        fi
        echo -e "\033[32mok\033[0m"
        ;;
    2|ssh)
        clone_lucy_repo "git@github.com:" "lucy_devtools"
        echo -ne "Cloning lucy ros packages "
        if ! $CURL -fsSL "https://raw.githubusercontent.com/Sentience-Robotics/lucy_devtools/refs/heads/master/lucy_utils/lucy.ssh.repos" | $VCS import src > /dev/null 2> /tmp/lucy_init.log; then
            echo -ne "\033[31mko\033[0m"
            cat /tmp/lucy_init.log
            exit 1
        fi
        echo -e "\033[32mok\033[0m"
        ;;
    *)
        echo -e "\033[31mThis method does not exists.\033[0m"
        exit 1
esac

# Setting up the environment

cat > .rosdistro.env << 'EOF'
export ROS_DISTRO="humble"
EOF

cat > .envrc << 'EOF'
export VERSION="0.1.0"
export LUCY="$(pwd)"
export LUCY_UROS_PICO="$LUCY/src/lucy_micro_ros_pico"
export LUCY_ROS2="$LUCY/src/lucy_ros2"
export LUCY_DEVTOOLS="$LUCY/lucy_devtools"
export LUCY_DOCKER="$LUCY_DEVTOOLS/lucy_docker"
export LUCY_UTILS="$LUCY_DEVTOOLS/lucy_utils"
export PATH="$PATH:$LUCY_UTILS"
source $LUCY/.rosdistro.env
EOF

source "$(pwd)/.envrc"

echo -ne "Setting up the environment "
if ! DIRENV=$(command -v direnv 2> /dev/null); then
    echo -e "\033[31mko.\033[0m"
    echo -e "direnv not found."
    exit 1
fi
if ! $DIRENV allow .; then
    echo -e "\033[31mko.\033[0m"
    exit 1
fi
echo -e "\033[32mok.\033[0m"

echo -ne "Setting up permissions "
find . -type d -exec chmod 0777 {} +
find . -type f -exec chmod 0666 {} +
chmod 777 ./lucy_devtools/lucy_utils/*
echo -e "\033[32mok.\033[0m"

# Chosing default distribution

ROS_DISTRIBUTIONS=("humble" "jazzy")

echo -ne "Choose a ros distribution (${ROS_DISTRIBUTIONS[*]}): "
read -r USER_ROS_DISTRIBUTION
USER_ROS_DISTRIBUTION=$(echo "$USER_ROS_DISTRIBUTION" | tr '[:upper:]' '[:lower:]')
if [[ -z "$USER_ROS_DISTRIBUTION" ]]; then
    echo -e "\033[31mYou must specify a ros distribution\033[0m"
    exit 1
fi

if [[ ! "${ROS_DISTRIBUTIONS[*]}" =~ $USER_ROS_DISTRIBUTION ]]; then
    echo -e "\033[31mThis ROS distribution doesn't exist or is not suported"
    echo -e "Supported distribution: (${ROS_DISTRIBUTIONS[*]})\033[0m"
    exit 1
fi

lucy_devtools/lucy_utils/ChangeEnv "$USER_ROS_DISTRIBUTION"
