#!/bin/bash

Header

display_help() {
    echo "Usage: Make [OPTIONS]... [TARGET]"
    echo
    echo "Options:"
    echo "  -h, --help      Show this help message"
    echo "  -b, --build     Build the project"
    echo "  -r, --rebuild   Rebuild the project"
    echo "  -c, --clean     Clean the build directory"
    echo "  -j, --jobs      Number of jobs to run simultaneously"
    echo "  --now           Skip the delay before cleaning"
}

clean() {
    cd $LUCY
    stopwatch=$DELAY_BEFORE_PURGE
    while [[ $stopwatch -gt 0 ]]; do
        echo -e "Cleaning the build directory in $stopwatch seconds..."
        sleep 1
        ((stopwatch--))
    done
    rm -r install
    rm -r build
    rm -r log
}

#build_cmake() {
#    if [[ ! -f "CMakeLists.txt" ]]; then
#        echo "CMakeLists.txt not found. Please run this script from the project root directory."
#        exit 1
#    fi
#    if [[ -z "$PRESET_FLAG" ]]; then
#        echo -e "\033[33mNo preset defined\033[0m"
#    fi
#    if [[ ! -d "$BUILD_DIR" ]]; then
#        echo -e "\033[32mBuild directory $BUILD_DIR does not exist. Creating it...\033[0m"
#        mkdir -p $BUILD_DIR
#    fi
#    {
#        cd $BUILD_DIR
#        $CMAKE $PRESET_FLAG ..
#        if [[ "$?" -ne 0 ]]; then
#            echo -e "\033[31mCMake configuration failed.\033[0m"
#            exit 1
#        else
#            echo -e "\033[32mCMake configuration succeeded.\033[0m"
#        fi
#        $CMAKE --build . -- -j $JOBS
#        if [[ "$?" -ne 0 ]]; then
#            echo -e "\033[31mBuild failed.\033[0m"
#            exit 1
#        else
#            echo -e "\033[32mBuild succeeded.\033[0m"
#        fi
#    }
#}

build_colcon() {
    cd $LUCY
    COLCON=$(command -v colcon 2> /dev/null)
    if [[ -z "$COLCON" ]]; then
        echo -e "\033[31mcolcon not found. Please install colcon.\033[0m"
        exit 1
    fi
    $COLCON build --parallel-workers $JOBS
}

generate_ctags() {
    CTAGS=$(command -v ctags 2> /dev/null)
    if [[ $? -ne 0 ]]; then
        echo -e "\033[31mctags not found. Please install ctags.\033[0m"
        exit 1
    fi
    $CTAGS -R --exclude=external --exclude=build
}



CMAKE=$(command -v cmake 2> /dev/null)
if [[ $? -ne 0 ]]; then
    echo -e "\033[31mCMake not found. Please install CMake.\033[0m"
    exit 1
fi

OPTIONS=":hbrcj:"
LONGOPTS="help,build,rebuild,clean,jobs:,now"
OPTS=$(getopt --name "$0" -o $OPTIONS -l $LONGOPTS -- "$@")
if [[ $? -ne 0 ]]; then
    display_help
    exit 1
fi

TARGET="none"
JOBS=1
DELAY_BEFORE_PURGE=3

eval set -- "$OPTS"

while true; do
    case "$1" in
        -h|--help)
            display_help
            shift 1
            exit 0
            ;;
        -b|--build)
            if [[ "$TARGET" != "none" ]]; then
                echo "\033[31mMultiple targets specified. Please choose only one.\033[0m"
                exit 1
            fi
            TARGET="build"
            shift 1
            ;;
        -r|--rebuild)
            if [[ "$TARGET" != "none" ]]; then
                echo "Multiple targets specified. Please choose only one."
                exit 1
            fi
            TARGET="rebuild"
            shift 1
            ;;
        -c|--clean)
            if [[ "$TARGET" != "none" ]]; then
                echo "Multiple targets specified. Please choose only one."
                exit 1
            fi
            TARGET="clean"
            shift 1
            ;;
        -j|--jobs)
            if [[ -z "$2" ]]; then
                echo $2
                JOBS=$(nproc --all)
                shift 1
            fi
            if [[ "$2" =~ ^[0-9]+$ ]]; then
                JOBS="$2"
                shift 2
            else
                echo "Invalid number of jobs: $2"
                exit 1
            fi
            ;;
        --now)
            DELAY_BEFORE_PURGE=0
            shift 1
            ;;
        --)
            shift
            break
            ;;
        *)
            echo "Invalid option: $1"
            display_help
            exit 1
            ;;
    esac
done

if [[ "$TARGET" == "none" ]]; then
    echo -e "No target specified. Use -b, -r, or -c."
    exit 1
fi

if [[ "$TARGET" == "clean" || "$TARGET" == "rebuild" ]]; then
    clean
fi

if [[ "$TARGET" == "build" || "$TARGET" == "rebuild" ]]; then
    build_colcon
fi
